name: udev
description: API for enumerating and introspecting local devices
homepage: https://www.freedesktop.org/software/systemd/man/libudev.html
repository: https://github.com/canonical/udev.dart
issue_tracker: https://github.com/canonical/udev.dart/issues
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  ffi: ^2.0.1
  meta: ^1.7.0

dev_dependencies:
  ffigen: ^6.0.1
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.17.7
